import shutil
import json
import os
from pathlib import Path

SOURCE_HUB = Path("notebooks") 
DEST_PIP = Path("src/ptyrad/starter/notebooks")
DEST_DOCS = Path("docs/workflow") 

def clean_notebook(file_path):
    """
    Reads a notebook, clears all outputs and execution counts, 
    and saves it back to disk.
    """
    with open(file_path, "r", encoding="utf-8") as f:
        nb = json.load(f)

    for cell in nb.get("cells", []):
        if cell.get("cell_type") == "code":
            cell["outputs"] = []
            cell["execution_count"] = None

    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
        f.write("\n")

def main():
    if not SOURCE_HUB.exists():
        print(f"❌ Source not found: {SOURCE_HUB}")
        return

    # --- 1. Clean Pip Destination ---
    # It is safe to wipe the src/ copy because it is 100% autogenerated.
    # This ensures no "ghost" files remain if you rename a tutorial.
    if DEST_PIP.exists():
        shutil.rmtree(DEST_PIP)
    DEST_PIP.mkdir(parents=True)

    # --- 2. Prepare Docs Destination ---
    # ⚠️ DO NOT wipe this folder, or you will lose index.md!
    DEST_DOCS.mkdir(parents=True, exist_ok=True)
    
    # Optional: Clean up OLD notebooks from docs/ to prevent duplicates.
    # This deletes only .ipynb files in dest that are no longer in source.
    source_filenames = {p.name for p in SOURCE_HUB.glob("*.ipynb")}
    for existing_nb in DEST_DOCS.glob("*.ipynb"):
        if existing_nb.name not in source_filenames:
            print(f"   🗑️  Removing stale file: {existing_nb.name}")
            os.remove(existing_nb)

    print(f"🚀 Syncing from Root '{SOURCE_HUB}'...")

    for nb_path in SOURCE_HUB.glob("*.ipynb"):
        print(f"   📄 {nb_path.name}")

        # --- TASK A: Prepare for Docs (Overwrite Only) ---
        # This will replace the .ipynb file but leave index.md untouched.
        shutil.copy2(nb_path, DEST_DOCS / nb_path.name)
        
        # --- TASK B: Prepare for Pip (Strip Outputs) ---
        pip_path = DEST_PIP / nb_path.name
        shutil.copy2(nb_path, pip_path)
        clean_notebook(pip_path)

    print("✅ Sync complete!")
    print(f"   - Docs (Rich): {DEST_DOCS}")
    print(f"   - Pip  (Lean): {DEST_PIP}")

if __name__ == "__main__":
    main()